version: '3'

volumes:
  db_data: {}

services:
  db:
    image: postgres:9.6
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data

  web: &web
    image: 472554934874.dkr.ecr.us-east-1.amazonaws.com/{{project_name}}
    restart: always
    depends_on:
      - db
    env_file:
      - ./environment
    labels:
      - "traefik.backend={{project_name}}-web"
      - "traefik.frontend.rule=Host:{{project_name}}.civicadesarrolla.me"
      - "traefik.enable=true"
      - "traefik.port=3000"

  traefik:
    image: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
