FROM ruby:2.4.2-alpine

# Runtime
ENV HOME=/usr/src \
    LANG=C.UTF-8 \
    PATH=/usr/src/bin:$PATH \
    TERM='xterm-256color' \
    RAILS_ENV=development

WORKDIR $HOME

EXPOSE 3000

CMD rm -f tmp/pids/server.pid && rails server -b 0.0.0.0

STOPSIGNAL SIGKILL

RUN set -ex \
    && apk update \
    && apk upgrade \
    && apk add --no-cache --virtual .runtime \
      bash \
      imagemagick \
      less \
      nodejs \
      postgresql-dev \
      tzdata

# Build
RUN set -ex \
    && apk add --no-cache --virtual .build \
      ruby-dev \
      build-base \
      git

# vim: ft=dockerfile
