common: &default_settings
  license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
  app_name: {{project_name}}
  log_level: info

development:
  <<: *default_settings
  app_name: {{project_name}} (Development)
  monitor_mode: false

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings
  app_name: {{project_name}} (Staging)

production:
  <<: *default_settings
